### ISSUE TITLE
socket.io package.json emit problem

### ISSUE THREAD

**Issue by rayros** [alexisvincent/systemjs-hot-reloader#121]
**chokidar-socket-emitter**

`
    if (pjson) {
      socket.on('package.json', function (fn) {
        fn(pjson)
      })
    }
`

**systemjs-hot-reloader**
`      
this.socket.emit('package.json', (pjson) => {
  this.jspmConfigFile = pjson.jspm.configFile || 'config.js'
})
`

```
/home/master/workspace/chop/node_modules/chokidar-socket-emitter/server.js:62
      fn(pjson)
      ^

TypeError: fn is not a function
    at Socket.<anonymous> (/home/master/workspace/chop/node_modules/chokidar-socket-emitter/server.js:62:7)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at /home/master/workspace/chop/node_modules/socket.io/lib/socket.js:503:12
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by alexisvincent** [comment]
@capaj Why is this done anyway? I couldn't work out what you were do here.

@rayros I'm actually thinking we should remove the code that handles this case.

**Comment by rayros** [comment]
hi this code is unnecessary
