### ISSUE TITLE
async imports / System.import not resolving on reload

### ISSUE THREAD

**Issue by mpfau** [alexisvincent/systemjs-hot-reloader#129]
I'm currently switching over to the current release... :-)

Normal imports are resolved perfectly when a file is changed. However, everything imported via a System.import fails with the following error:

```
Error: parentKey.indexOf is not a function
  Resolving http://mpfau:9000/beta/client/build/app-import.js to 1
    at getParentMetadata (http://mpfau:9000/beta/client/node_modules/systemjs/dist/system.src.js:1587:42)
    at SystemJSLoader$1.normalize (http://mpfau:9000/beta/client/node_modules/systemjs/dist/system.src.js:1604:24)
    at http://mpfau:9000/beta/client/node_modules/systemjs/dist/system.src.js:321:27
From previous event:
    at eval (http://mpfau:9000/beta/client/node_modules/systemjs-hmr/dist/systemjs-hmr.js:12879:10)
From previous event:
    at eval (http://mpfau:9000/beta/client/node_modules/systemjs-hmr/dist/systemjs-hmr.js:12874:8)
```

## Steps to reproduce
1. npm install systemjs@0.20.9 systemjs-hot-reloader@1.1.0
2. Setup app.js, app-import.js and test.html as defined below
3. let chokidar-socket-emitter listen to the current dir and port 9082
4. open test.html in a browser
5. make a change to app-import.js and the error described above is triggered

#### app.js
```
SystemJS.import("app-import.js")
```

#### app-import.js
```
console.log("Test for alexis")
```

#### test.html
```
<html>
<head>
    <script src="../node_modules/systemjs/dist/system.src.js"></script>
    <script>
		System.config({
			"transpiler": false,
			"map": {
				"systemjs-hot-reloader": "../node_modules/systemjs-hot-reloader/dist/index.js",
				"systemjs-hmr": "../node_modules/systemjs-hmr/dist/systemjs-hmr.js",
			}
		})

		System.import('systemjs-hot-reloader').then(function (connect) {
			connect({host: location.protocol + '//' + location.hostname + ':9082'})

			return System.import('app.js')
		})
    </script>
</head>
</html>
```

**Comment by alexisvincent** [comment]
Thanks, will test tomorrow morning. This is an interesting case I haven't actually thought about. Assuming the bug you're seeing is fixed, I'm not sure how I will be able to determine that `app.js` has a dependency on `app-import.js`. Maybe @guybedford can make this show up in the trace api somehow?

**Comment by mpfau** [comment]
I debugged a bit and noticed that the function `Loader.prototype.resolve = function (key, parent)` (line 317 of system.src.js) is invoked by system-hmr with the array index of the entries array as `parentKey` if the deps of the module are empty.

I think that it would be nice if SystemJs would add dependencies for System.import statements, too.
As we use System.import statements only in a few places, a valid workaround would be to add the dependencies through an indirection (asyncImport) and setup the dependencies:
``` js
asyncImport(module.id, "app-import.js")

function asyncImport(importer, moduleName) {
	System.loads[System.resolveSync(importer)].deps.push(moduleName)
	System.loads[System.resolveSync(importer)].depMap[moduleName] = System.resolveSync(moduleName)
	return System.import(moduleName)
}
```

**Comment by alexisvincent** [comment]
@mpfau, that could work, but I have a feeling `deps` and `depMap` (we only use `depMap`) are reset every time. Might be wrong. Note, `System.import` optionally takes a parent address, which could be augmented to support adding values to `depMap`. Something like.

```js
System.import = function(moduleName, parentName) {
    if (parentName) {
       // add to depMap 
    }
    return System.proto.import.apply(System, [moduleName, parentName])
}
```

Then you could import via

```js
// see https://github.com/systemjs/systemjs/blob/master/docs/system-api.md#systemjsimportmodulename--normalizedparentname---promisemodule
System.import('./app-import.js', __moduleName)
```

perhaps @guybedford could rewrite `System.import('moduleName')` statements to `System.import('moduleName', __moduleName)` at compile/transpile time.

**Comment by alexisvincent** [comment]
Either way, having this in the trace API would be very useful.

**Comment by adelespinasse** [comment]
I'm getting a very similar error, but with normal ES6-style imports. In fact I think it's a basically identical error, except that the compiled version of system.js is being used instead of the debuggable source (I don't know how to change this):
```
Error: r.indexOf is not a function
  Resolving http://localhost:5000/src/util/userutil.js to 1
    at G (http://localhost:5000/jspm_packages/system.js:4:11953)
    at Ve.H [as normalize] (http://localhost:5000/jspm_packages/system.js:4:12147)
    at http://localhost:5000/jspm_packages/system.js:5:5036
From previous event:
    at eval (http://localhost:5000/jspm_packages/npm/systemjs-hmr@2.0.6/dist/systemjs-hmr.js:11188:12)
From previous event:
    at eval (http://localhost:5000/jspm_packages/npm/systemjs-hmr@2.0.6/dist/systemjs-hmr.js:11183:10)
```
I assumed I was doing something wrong, but seeing this bug report made me not so sure.

The first line of the stack trace (userutil.js line 1) seems unrelated to which source file was modified. The line referenced is `import md5 from 'blueimp-md5';` (importing a 3rd-party npm package). I assume it just happens to be the first node in the dependency graph or something. `userutil.js` is always imported via an ES6-style import when other files use it.

The above is what I get the first time a source file is modified after the app is loaded. After that any additional changes result in this error:
```
TypeError: Cannot read property '__reload' of undefined
    at eval (http://localhost:5000/jspm_packages/npm/systemjs-hmr@2.0.6/dist/systemjs-hmr.js:11167:104)
From previous event:
    at eval (http://localhost:5000/jspm_packages/npm/systemjs-hmr@2.0.6/dist/systemjs-hmr.js:11154:25)
```

**Comment by alexisvincent** [comment]
Fix coming in the next 30 min or so.

**Comment by alexisvincent** [comment]
Just recovering from a typo. Ran `rm -rf ~` instead of `rm -rf ./~`. Destroyed some of my home dir...

**Comment by alexisvincent** [comment]
Fixed in `systemjs-hmr` 2.0.8.

**Comment by alexisvincent** [comment]
Refurbishing this issue for async import support

**Comment by mpfau** [comment]
@alexisvincent thanks for fixing! I just tested successfully against system-hmr 2.0.8.

It looks like deps and depMap are reset every time. However, that is not a problem as the file is re-imported on change (and the dependencies are re-written to deps/depMap).

It would be nice, if @guybedford could adapt System.import according to your ideas when `System.trace == true`.

**Comment by alexisvincent** [comment]
Something else we could do is save these import mappings in a side table. However I think the best place for this would belong in the ES-Module-Loader trace implementation. @guybedford, would appreciate your input here.

**Comment by guybedford** [comment]
I've been experimenting with a dynamic deps trace in https://github.com/ModuleLoader/es-module-loader/commit/4f23167e02f4b449fad8fd8e0a53c53ea80e485d.

What we can do is catch all calls to the dynamic `import` (not `System.import`, but the contextual import when compiled with System.register) and know that it was made by the parent module.

I'm also not sure what use this information is to the hot reloader as well - there's no way to refresh the references once they have been returned from the import promise?

Perhaps just a direct tracing of top-level imports is all that is needed.

**Comment by alexisvincent** [comment]
@guybedford Awesome! Is there a reason that you would only support this for `import` and not `System.import` when a `parentKey` is provided? 

This would work for the hot-reloader as follows. In the example that @mpfau at the top of this issue, by listing `app-import.js` in the `depMap` entry of `app.js`, upon a change event for `app-import.js`, `app.js` would be detected as an `"importer"` of `app-import.js`, thus both would be deleted from the registry. Then `app.js` would be detected as the only dependency root and would be imported, which would call `System.import('app-import.js')`, which no longer exists in the registry and so would be reimported. Exactly as we would expect.

Not sure what you mean by
> Perhaps just a direct tracing of top-level imports is all that is needed.

**Comment by guybedford** [comment]
Ok, then the implementation I've got there should be a good start to play around with. It's not possible to tell when `System.import` is run within which module, as there is no global context available to get its calling site. So this is only something we can support for the `import` method.

System.import with a parent key can be used for arbitrary relative normalization, without implying that it is within the given module.

**Comment by alexisvincent** [comment]
Right, of course. Awesome, would this be able to make its way into a version of SystemJS? Perhaps via a flag, for general testing?

**Comment by guybedford** [comment]
@alexisvincent this will be shipping in the next SystemJS release, which should be soon.
